FROM python:3.7-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load the DagsterInstance


RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

WORKDIR /opt/dagster/app

COPY requirements.txt .env /opt/dagster/app

RUN pip install -r requirements.txt

COPY /fpl_dagster .env /opt/dagster/app/fpl_dagster

WORKDIR /opt/dagster/app/fpl_dagster

# Run dagster gRPC server on port 4000

EXPOSE 4000

# HEALTHCHECK --interval=1s --timeout=3s --retries=10 CMD  curl --fail http://localhost:4000 || exit 1
# HEALTHCHECK CMD curl --fail http://localhost:4000
# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]

#"--inject-env-vars-from-instance"